# Generated by Django 5.0.6 on 2024-05-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_sav',
            fields=[
                ('idclient', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField(auto_now=True)),
                ('est_personne_morale', models.BooleanField(default=False)),
                ('raison_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('nom_final', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('idpartenaire', models.BigAutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=30, unique=True, verbose_name='Marque')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('idpersonnel', models.BigAutoField(primary_key=True, serialize=False)),
                ('poste', models.CharField(blank=True, max_length=30, null=True, verbose_name='Poste')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Telephone')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sav_request',
            fields=[
                ('idrequest', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_sav', models.CharField(choices=[('DEVEA', 'DEVEA'), ('Non DEVEA', 'Non DEVEA')], default='DEVEA', max_length=20, verbose_name='Type SAV')),
                ('numero_dossier', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='N° de Dossier')),
                ('numero_serie', models.CharField(blank=True, max_length=30, null=True, verbose_name='N° de Serie')),
                ('reference', models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference')),
                ('designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation')),
                ('garantie', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='oui', max_length=10, verbose_name='Garantie')),
                ('description_piece', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descr Pièce')),
                ('reference_piece', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ref Pièce')),
                ('pop', models.CharField(blank=True, max_length=30, verbose_name='POP')),
                ('status', models.CharField(default='Diagnostique interne', max_length=50, verbose_name='Statut')),
                ('observation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Observation')),
                ('validation_client', models.BooleanField(default=False)),
                ('rapport_technique', models.ImageField(blank=True, null=True, upload_to='sav/rapport_technique/%Y/%m/%d/')),
                ('facture_fornisseur', models.ImageField(blank=True, null=True, upload_to='sav/facture_fournissseur/%Y/%m/%d/')),
                ('facture_proforma', models.ImageField(blank=True, null=True, upload_to='sav/facture_proforma/%Y/%m/%d/')),
                ('bon_pour_accord', models.BooleanField(default=False)),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date Sortie')),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_sav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.client_sav')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='serviceapresvente.partenaires')),
                ('resp_sav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.personnels')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
