# Generated by Django 5.0.6 on 2024-10-05 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ol', models.CharField(blank=True, max_length=255, null=True)),
                ('ccial', models.CharField(blank=True, max_length=255, null=True)),
                ('fact', models.CharField(blank=True, max_length=255, null=True)),
                ('bdc', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('qte_dde', models.PositiveIntegerField(default=0)),
                ('stock_initial', models.PositiveBigIntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is delete')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['reference'], name='serviceapre_referen_ad1579_idx'), models.Index(fields=['date'], name='serviceapre_date_b7f1d7_idx')],
            },
        ),
    ]
