# Generated by Django 5.0.6 on 2024-10-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facturation',
        ),
    ]
