# Generated by Django 5.0.6 on 2024-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0002_sav_request_numero_fiche_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sav',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
