# Generated by Django 5.0.6 on 2024-05-30 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0002_fournisseurs_alter_sav_request_facture_fornisseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblageReparation',
            fields=[
                ('idAssemblage', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Terminé', 'Terminé'), ('Non Terminé', 'Non Terminé'), ('En cour', 'En cour')], default='Non Terminé', max_length=30, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonClient',
            fields=[
                ('idLivraisonClient', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Livré', 'Livré'), ('Non Livré', 'Non Livré')], default='Non Livré', max_length=30, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assamblagereparation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assamblagereparations', to='serviceapresvente.assemblagereparation')),
            ],
        ),
        migrations.CreateModel(
            name='Devea',
            fields=[
                ('idRecouvrement', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_dhl', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Marque')),
                ('facture_transitaire', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Marque')),
                ('fichier_dossier_dhl', models.ImageField(blank=True, null=True, upload_to='sav/dhl/%Y/%m/%d/')),
                ('fichier_facture_fornisseur', models.ImageField(blank=True, null=True, upload_to='sav/facture_transitaire/%Y/%m/%d/')),
                ('autre_piece', models.ImageField(blank=True, null=True, upload_to='sav/autres_pieces/%Y/%m/%d/')),
                ('est_recouvert', models.CharField(choices=[('Recouvrement OK', 'Recouvrement OK'), ('Recouvrement Non OK', 'Recouvrement Non OK')], default='Recouvrement Non OK', max_length=30, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livraisonclient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraisonclients2', to='serviceapresvente.livraisonclient')),
            ],
        ),
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('idRecouvrement', models.BigAutoField(primary_key=True, serialize=False)),
                ('est_recouvert', models.CharField(choices=[('Recouvrement OK', 'Recouvrement OK'), ('Recouvrement Non OK', 'Recouvrement Non OK')], default='Recouvrement Non OK', max_length=30, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livraisonclient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraisonclients', to='serviceapresvente.livraisonclient')),
            ],
        ),
        migrations.CreateModel(
            name='ClotureDossier',
            fields=[
                ('idClotureDossier', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_cloture', models.DateField(auto_now=True)),
                ('cloture_dossier', models.CharField(choices=[('Clôtuté', 'Clôturé'), ('Non Clôturé', 'Non Clôturé')], default='Non Clôturé', max_length=30, verbose_name='Clôture Dossier')),
                ('flag', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recouvrement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='serviceapresvente.recouvrement')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviCommandeSav',
            fields=[
                ('idSuiviCommande', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Commande placée', 'Commande placée'), ('Réception dépôt France ', 'Réception dépôt France'), ('Reception dépôt Dubaï ', 'Réception dépôt Dubaï'), ('Sous Douane Malienne', 'Sous Douane Malienne'), ('Reçu', 'Reçu')], default='Commande placée', max_length=30, verbose_name='Statut')),
                ('flag', models.BooleanField(default=False)),
                ('nombre_jour', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('commandesav', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commandesavs', to='serviceapresvente.commandesav')),
            ],
        ),
        migrations.AddField(
            model_name='assemblagereparation',
            name='suivicommandesav',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivicommandesavs', to='serviceapresvente.suivicommandesav'),
        ),
    ]
