# Generated by Django 5.0.6 on 2024-05-31 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0003_assemblagereparation_livraisonclient_devea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_sav',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='client_sav',
            name='nom_final',
        ),
        migrations.AddField(
            model_name='client_sav',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client_sav',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_sav',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='observation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=400)], verbose_name='Observation'),
        ),
    ]
