# Generated by Django 5.0.6 on 2024-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0006_remove_sav_request_date_cloture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_request',
            name='validation_client',
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='garantie',
            field=models.CharField(choices=[('Sous garantie', 'Sous garantie'), ('hors garantie', 'hors garantie')], default='Sous garantie', max_length=20, verbose_name='Garantie'),
        ),
    ]
