# Generated by Django 5.0.6 on 2024-08-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapresvente", "0008_remove_client_sav_email_alter_client_sav_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sav_request",
            name="client_sav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.client_sav",
            ),
        ),
        migrations.AlterField(
            model_name="sav_request",
            name="resp_sav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.personnels",
            ),
        ),
    ]
