# Generated by Django 5.0.6 on 2024-08-30 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapresvente", "0009_alter_sav_request_client_sav_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_sav",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="commandesav",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fournisseurs",
                to="serviceapresvente.fournisseurs",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.client_sav",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.personnels",
            ),
        ),
        migrations.AlterField(
            model_name="instance_recouvrement",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.instance",
            ),
        ),
        migrations.AlterField(
            model_name="sav_request",
            name="client_sav",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.client_sav",
            ),
        ),
        migrations.AlterField(
            model_name="sav_request",
            name="marque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.partenaires",
            ),
        ),
        migrations.AlterField(
            model_name="sav_request",
            name="resp_sav",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="serviceapresvente.personnels",
            ),
        ),
    ]
