# Generated by Django 5.0.6 on 2024-06-06 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0010_alter_commandesav_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_request',
            name='observation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)], verbose_name='Observation'),
        ),
    ]
