# Generated by Django 5.0.6 on 2024-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0013_alter_sav_request_rapport_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblagereparation',
            name='statut',
            field=models.CharField(choices=[('pending (DSI - Assemblage)', 'pending (DSI - Assemblage)'), ('Terminé', 'Terminé')], default='pending (DSI - Assemblage)', max_length=30, verbose_name='Statut'),
        ),
    ]
