# Generated by Django 5.0.6 on 2024-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0014_alter_assemblagereparation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisonclient',
            name='statut',
            field=models.CharField(choices=[('Sav livré', 'Sav livré'), ('Sav non livré(e)', 'Sav non livré(e)')], default='Sav non livré(e)', max_length=30, verbose_name='Statut'),
        ),
    ]
