# Generated by Django 5.0.6 on 2024-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0015_alter_livraisonclient_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisonclient',
            name='statut',
            field=models.CharField(choices=[('Sav livré', 'Sav livré'), ('Sav non livré', 'Sav non livré')], default='Sav non livré', max_length=30, verbose_name='Statut'),
        ),
    ]
