# Generated by Django 5.0.6 on 2024-06-12 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0017_alter_recouvrement_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraisonclient',
            name='bordereau_livraison',
            field=models.ImageField(blank=True, null=True, upload_to='sav/rapport_techniques/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='facture_client',
            field=models.ImageField(blank=True, null=True, upload_to='sav/factures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraisonclient',
            name='commentaire',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50)]),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='commentaire',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=50)]),
        ),
    ]
