# Generated by Django 5.0.6 on 2024-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0019_remove_cloturedossier_recouvrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrement',
            name='autre_piece',
            field=models.ImageField(blank=True, null=True, upload_to='sav/autres_pieces/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='deveaOrder',
            field=models.CharField(default='0000', max_length=30, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='facture_transitaire',
            field=models.ImageField(blank=True, null=True, upload_to='sav/facture_transitaire/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='fichier_dossier_dhl',
            field=models.ImageField(blank=True, null=True, upload_to='sav/dhl/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='is_devea_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_facture_transitaire',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant transitaire'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='numero_dhl',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero DHL'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='statutDevea',
            field=models.CharField(choices=[('facturation HP, a completer', 'facturation HP, a completer'), ('Dossier HP  complet', 'Dossier HP  complet'), ('payé', 'payé'), ('non payé', 'non payé')], default='facturation HP, a completer', max_length=40, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='transitaire',
            field=models.CharField(choices=[('TANSIT1', 'TANSIT1'), ('TANSIT2', 'TANSIT2')], default='TANSIT1', max_length=40, verbose_name='Statut'),
        ),
    ]
