# Generated by Django 5.0.6 on 2024-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0020_recouvrement_autre_piece_recouvrement_deveaorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrement',
            name='fees1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Autre Montant 1'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='fees2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Autre Montant 2'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='fees3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Autre Montant 3'),
        ),
        migrations.AlterField(
            model_name='livraisonclient',
            name='bordereau_livraison',
            field=models.ImageField(blank=True, null=True, upload_to='sav/bordereau_livraison/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_client',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_facture_transitaire',
            field=models.FloatField(default=0, verbose_name='Montant transitaire'),
        ),
    ]
