# Generated by Django 5.0.6 on 2024-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0021_recouvrement_fees1_recouvrement_fees2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recouvrement',
            old_name='fees2',
            new_name='droit_douane',
        ),
        migrations.RenameField(
            model_name='recouvrement',
            old_name='montant_facture_transitaire',
            new_name='montant_prestation',
        ),
        migrations.RenameField(
            model_name='recouvrement',
            old_name='fees1',
            new_name='remise_documentaire',
        ),
        migrations.RenameField(
            model_name='recouvrement',
            old_name='fees3',
            new_name='transport',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='fichier_dossier_dhl',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='numero_dhl',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='numero_awd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero DHL AWD'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='statutDevea',
            field=models.CharField(choices=[('facturation HP, a completer', 'facturation HP, a completer'), ('Dossier HP  complet', 'Dossier HP  complet'), ('Dossier HP payé', 'Dossier HP payé'), ('Dossier HP non payé', 'Dossier HP non payé')], default='facturation HP, a completer', max_length=40, verbose_name='Statut'),
        ),
    ]
