# Generated by Django 5.0.6 on 2024-06-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0022_rename_fees2_recouvrement_droit_douane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='droit_douane',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Droit douane'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='remise_documentaire',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Remise documentaire'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='transport',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Transport'),
        ),
    ]
