# Generated by Django 5.0.6 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0024_rename_date_cloture_cloturedossier_resp_dossier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloturedossier',
            old_name='Client',
            new_name='client',
        ),
    ]
