# Generated by Django 5.0.6 on 2024-06-25 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0027_alter_cloturedossier_resp_dossier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('idinstance', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_instance', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default='Externe', max_length=20, verbose_name='Instance')),
                ('numero_dossier', models.CharField(max_length=30, verbose_name='N° de Dossier')),
                ('action', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100)], verbose_name='Action')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En cour', 'En cour'), ('Recouvrement', 'Recouvrement'), ('Décision DG', 'Décision DG'), ('Clôturé', 'Clôturé'), ('Non résolu', 'Non résolu')], default='En cour', max_length=20, verbose_name='Statut')),
                ('is_facturable', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('flag2', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.client_sav')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instance_recouvrement',
            fields=[
                ('idrecouv', models.BigAutoField(primary_key=True, serialize=False)),
                ('facture_reference', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='N° facture')),
                ('facture_montant', models.FloatField(default=0, verbose_name='Montant')),
                ('facture_paiement', models.CharField(choices=[('Payé', 'Payé'), ('Non Payé', 'Non Payé')], default='Non Payé', max_length=20, verbose_name='Paiement')),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.instance')),
            ],
        ),
    ]
