# Generated by Django 5.0.6 on 2024-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0029_rename_facture_paiement_instance_recouvrement_facture_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='rapport_technique',
            field=models.ImageField(blank=True, null=True, upload_to='instance/%Y/%m/%d/'),
        ),
    ]
