# Generated by Django 5.0.6 on 2024-06-26 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0030_instance_rapport_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='description',
        ),
        migrations.AddField(
            model_name='instance',
            name='Responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.personnels'),
        ),
        migrations.AddField(
            model_name='instance',
            name='besoin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Besoin'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='action',
            field=models.TextField(default=1, validators=[django.core.validators.MaxLengthValidator(limit_value=100)], verbose_name='Action'),
            preserve_default=False,
        ),
    ]
