# Generated by Django 5.0.6 on 2024-06-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0031_remove_instance_description_instance_responsable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='Responsable',
            new_name='responsable',
        ),
    ]
