# Generated by Django 5.0.6 on 2024-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0032_rename_responsable_instance_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='email',
            field=models.EmailField(blank=True, default='sav@soprescom.net', max_length=30, null=True, unique=True, verbose_name='Email'),
        ),
    ]
