# Generated by Django 5.0.6 on 2024-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_mega',
            field=models.BooleanField(default=False),
        ),
    ]
