# Generated by Django 5.0.6 on 2024-09-04 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_quantite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stockLimite', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_mvt', models.DateTimeField(auto_now_add=True)),
                ('stock_produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
