# Generated by Django 5.0.6 on 2024-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_solde_regular_product_regular_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='solde_price',
            field=models.FloatField(),
        ),
    ]
