# Generated by Django 5.0.6 on 2024-09-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_name'),
        ('shop', '0003_alter_product_slug'),
    ]

    operations = [
    ]
