# Generated by Django 5.0.6 on 2024-05-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_regular_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.TextField(max_length=4)),
                ('taxe_rate', models.FloatField()),
                ('logo', models.ImageField(upload_to='setting_image')),
                ('street', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('code_postal', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
