# Generated by Django 5.0.6 on 2024-05-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_setting_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(default='info@soprescom.net', max_length=100),
        ),
    ]
