# Generated by Django 5.0.6 on 2024-10-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produit_stock', to='shop.product'),
        ),
    ]
