# Generated by Django 5.0.6 on 2024-10-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_stock_stock_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
