# Generated by Django 5.0.6 on 2024-10-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0001_initial'),
        ('shop', '0008_product_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ol', models.CharField(blank=True, max_length=255, null=True)),
                ('ccial', models.CharField(blank=True, max_length=255, null=True)),
                ('fact', models.CharField(blank=True, max_length=255, null=True)),
                ('bdc', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('qte_dde', models.PositiveIntegerField(default=0)),
                ('stock_initial', models.PositiveBigIntegerField(default=0)),
                ('observation', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='serviceapresvente.client_sav')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['reference'], name='shop_sortie_referen_f94bee_idx'), models.Index(fields=['date'], name='shop_sortie_date_f2cc5c_idx')],
            },
        ),
    ]
