# Generated by Django 5.0.6 on 2024-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sortielivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortielivraison',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is delete'),
        ),
    ]
