# Generated by Django 5.0.6 on 2024-10-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_actionlog_type'),
        ('shop', '0010_sortielivraison_is_deleted'),
    ]

    operations = [
    ]
