# Generated by Django 5.0.6 on 2024-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_merge_20241004_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortielivraison',
            name='nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sortielivraison',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
