# Generated by Django 5.0.6 on 2024-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_mega',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
