# Generated by Django 5.0.6 on 2024-10-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_merge_20241004_1302'),
        ('shop', '0012_sortielivraison_nature_sortielivraison_serial_number'),
    ]

    operations = [
    ]
