# Generated by Django 5.0.6 on 2024-05-30 16:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('adresse', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='facture_fornisseur',
            field=models.ImageField(blank=True, null=True, upload_to='sav/facture_fournissseurs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='facture_proforma',
            field=models.ImageField(blank=True, null=True, upload_to='sav/facture_proformas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='rapport_technique',
            field=models.ImageField(blank=True, null=True, upload_to='sav/rapport_techniques/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('idfacturation', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference_facture', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('facture_proforma', models.ImageField(blank=True, null=True, upload_to='sav/factures/%Y/%m/%d/')),
                ('bon_pour_accord', models.BooleanField(blank=True, default=False, null=True, verbose_name='Bon Pour Accord')),
                ('est_paye', models.BooleanField(blank=True, default=False, null=True)),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savrequest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='serviceapresvente.sav_request')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeSav',
            fields=[
                ('idCommandePiece', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_jour', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savrequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sav_requests', to='serviceapresvente.sav_request')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs', to='serviceapresvente.fournisseurs')),
            ],
        ),
    ]
