# Generated by Django 5.0.6 on 2024-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0004_remove_client_sav_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='departement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Département'),
        ),
    ]
