# Generated by Django 5.0.6 on 2024-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0005_personnels_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_request',
            name='date_cloture',
        ),
    ]
