# Generated by Django 5.0.6 on 2024-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0008_rename_facture_fornisseur_sav_request_facture_fournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblagereparation',
            old_name='idAssemblage',
            new_name='idassemblage',
        ),
        migrations.RenameField(
            model_name='cloturedossier',
            old_name='idClotureDossier',
            new_name='idcloturedossier',
        ),
        migrations.RenameField(
            model_name='commandesav',
            old_name='idCommandePiece',
            new_name='idcommandesav',
        ),
        migrations.RenameField(
            model_name='devea',
            old_name='idRecouvrement',
            new_name='iddevea',
        ),
        migrations.RenameField(
            model_name='livraisonclient',
            old_name='idLivraisonClient',
            new_name='idlivraisonclient',
        ),
        migrations.RenameField(
            model_name='recouvrement',
            old_name='idRecouvrement',
            new_name='idrecouvrement',
        ),
        migrations.RenameField(
            model_name='sav_request',
            old_name='status',
            new_name='statut',
        ),
        migrations.RenameField(
            model_name='suivicommandesav',
            old_name='idSuiviCommande',
            new_name='idsuivicommandesav',
        ),
        migrations.RemoveField(
            model_name='cloturedossier',
            name='cloture_dossier',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='est_recouvert',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='est_recouvert',
        ),
        migrations.AddField(
            model_name='cloturedossier',
            name='statut',
            field=models.CharField(choices=[('clôtuté', 'clôturé'), ('Non clôturé', 'non clôturé')], default='Non clôturé', max_length=30, verbose_name='Clôture Dossier'),
        ),
        migrations.AddField(
            model_name='commandesav',
            name='statut',
            field=models.CharField(default='pending', max_length=50, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='devea',
            name='status',
            field=models.CharField(choices=[('payé', 'payé'), ('non payé', 'non payé')], default='non payé', max_length=30, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='statut',
            field=models.CharField(choices=[('payé', 'payé'), ('non payé', 'non payé')], default='non payé', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='assemblagereparation',
            name='statut',
            field=models.CharField(default='pending', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='livraisonclient',
            name='statut',
            field=models.CharField(choices=[('livré(e)', 'livré(e)'), ('non Livré(e)', 'non Livré(e)')], default='non Livré(e)', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sav_request',
            name='rapport_technique',
            field=models.ImageField(default=None, upload_to='sav/rapport_techniques/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suivicommandesav',
            name='statut',
            field=models.CharField(default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
