# Generated by Django 5.0.6 on 2024-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0011_alter_sav_request_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblagereparation',
            name='statut',
            field=models.CharField(choices=[('pending (DSI)', 'pending (DSI)'), ('Terminé', 'Terminé')], default='pending (DSI)', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commandesav',
            name='statut',
            field=models.CharField(choices=[('commande placée', 'commande placée'), ('pending (achat)', 'pending (achat)')], default='pending (achat)', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='suivicommandesav',
            name='statut',
            field=models.CharField(choices=[('pending (logistique)', 'pending (logistique)'), ('Réception dépôt France ', 'Réception dépôt France'), ('Reception dépôt Dubaï ', 'Réception dépôt Dubaï'), ('Sous Douane Malienne', 'Sous Douane Malienne'), ('Reçu', 'Reçu')], default='pending (logistique)', max_length=30, verbose_name='Statut'),
        ),
    ]
