# Generated by Django 5.0.6 on 2024-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0012_alter_assemblagereparation_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_request',
            name='rapport_technique',
            field=models.ImageField(blank=True, null=True, upload_to='sav/rapport_techniques/%Y/%m/%d/'),
        ),
    ]
