# Generated by Django 5.0.6 on 2024-06-11 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0016_alter_livraisonclient_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='commentaire',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='statut',
            field=models.CharField(choices=[('Sav payé', 'Sav payé'), ('Sav non payé', 'Sav non payé')], default='Sav non payé', max_length=30, verbose_name='Statut'),
        ),
    ]
