# Generated by Django 5.0.6 on 2024-06-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0025_rename_client_cloturedossier_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloturedossier',
            old_name='Numero_Dossier',
            new_name='numero_dossier',
        ),
    ]
