# Generated by Django 5.0.6 on 2024-06-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0028_instance_instance_recouvrement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance_recouvrement',
            old_name='facture_paiement',
            new_name='facture_statut',
        ),
    ]
