# Generated by Django 5.0.6 on 2024-05-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_orderdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderdetail',
            new_name='Orderdetails',
        ),
    ]
