# Generated by Django 5.0.6 on 2024-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_orderdetail_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('more_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='payment_methodes/%Y/%m/%d/')),
                ('test_public_key', models.CharField(max_length=255)),
                ('test_private_key', models.CharField(max_length=255)),
                ('prod_public_key', models.CharField(max_length=255)),
                ('prod_private_key', models.CharField(max_length=255)),
                ('is_available', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
