# Generated by Django 5.0.6 on 2024-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='method',
            name='prod_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='prod_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
