# Generated by Django 5.0.1 on 2024-09-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingdeploiement',
            name='clientleasing',
        ),
        migrations.RemoveField(
            model_name='leasingconsommable',
            name='categorieproduit',
        ),
        migrations.RemoveField(
            model_name='leasingconsommable',
            name='userLog',
        ),
        migrations.RemoveField(
            model_name='leasingconsommableexploitation',
            name='consommable',
        ),
        migrations.RemoveField(
            model_name='leasingexploitation',
            name='consommables',
        ),
        migrations.AlterUniqueTogether(
            name='leasingconsommableexploitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leasingconsommableexploitation',
            name='exploitation',
        ),
        migrations.RemoveField(
            model_name='leasingdeploiement',
            name='listeimprimante',
        ),
        migrations.RemoveField(
            model_name='leasingdeploiement',
            name='userLog',
        ),
        migrations.RemoveField(
            model_name='leasingexploitation',
            name='deploiement',
        ),
        migrations.RemoveField(
            model_name='leasinglisteimprimante',
            name='userLog',
        ),
        migrations.DeleteModel(
            name='LeasingClient',
        ),
        migrations.DeleteModel(
            name='LeasingConsommable',
        ),
        migrations.DeleteModel(
            name='LeasingConsommableExploitation',
        ),
        migrations.DeleteModel(
            name='LeasingDeploiement',
        ),
        migrations.DeleteModel(
            name='LeasingExploitation',
        ),
        migrations.DeleteModel(
            name='LeasingListeimprimante',
        ),
    ]
