# Generated by Django 5.0.1 on 2024-09-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0012_alter_client_sav_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingClient',
            fields=[
                ('idclientleasing', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('localite', models.CharField(max_length=20, verbose_name='Région')),
                ('refcontrat', models.CharField(max_length=20, unique=True, verbose_name='N° Contrat ')),
                ('duree_contrat', models.CharField(max_length=10, unique=True, verbose_name='Durée Contrat ')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date Contrat')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingConsommable',
            fields=[
                ('idconsommable', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('bordereausortie', models.CharField(max_length=30, verbose_name='Bordereau SOP')),
                ('typeproduit', models.CharField(max_length=30, verbose_name='Produit')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=50, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('modele', models.CharField(db_index=True, max_length=30, verbose_name='Modele')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('seuilLimite', models.IntegerField(default=5, verbose_name='Seuil')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingConsommableExploitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapresvente.leasingconsommable')),
            ],
        ),
        migrations.CreateModel(
            name='LeasingDeploiement',
            fields=[
                ('iddeploiement', models.BigAutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(db_index=True, max_length=50, verbose_name='Site')),
                ('adresseip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse IP')),
                ('date_deploiement', models.DateField(blank=True, null=True, verbose_name='Date Deploiement')),
                ('clientleasing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.leasingclient')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingExploitation',
            fields=[
                ('idexploitation', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_exploitation', models.DateField(auto_now=True)),
                ('intervention', models.CharField(choices=[('Remplacement consommable', 'Remplacement consommable'), ('Releve fin du mois', 'Releve fin du mois'), ('Fourniture Carton Papier', 'Fourniture Carton Papier')], default='Fourniture Carton Papier', max_length=50, verbose_name='Intervention')),
                ('pourcentage_toner', models.CharField(blank=True, max_length=5, null=True, verbose_name='Toner (%)')),
                ('ancien_index', models.IntegerField(blank=True, null=True)),
                ('nouvel_index', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(max_length=200, verbose_name='Observation')),
                ('consommables', models.ManyToManyField(through='serviceapresvente.LeasingConsommableExploitation', to='serviceapresvente.leasingconsommable')),
                ('deploiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.leasingdeploiement')),
            ],
        ),
        migrations.AddField(
            model_name='leasingconsommableexploitation',
            name='exploitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapresvente.leasingexploitation'),
        ),
        migrations.CreateModel(
            name='LeasingListeimprimante',
            fields=[
                ('idlisteimprimante', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Numeoro Série')),
                ('reference', models.CharField(db_index=True, max_length=50, verbose_name='Référence')),
                ('designation', models.CharField(db_index=True, max_length=50, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name='Date Acquisition')),
                ('garantie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Garantie')),
                ('endoflife', models.DateField(blank=True, null=True, verbose_name='End of Life')),
                ('flag', models.BooleanField(default=False)),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leasingdeploiement',
            name='listeimprimante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceapresvente.leasinglisteimprimante'),
        ),
        migrations.AddField(
            model_name='leasingconsommable',
            name='categorieproduit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='serviceapresvente.leasinglisteimprimante', verbose_name='Catégorie'),
        ),
        migrations.AlterUniqueTogether(
            name='leasingconsommableexploitation',
            unique_together={('exploitation', 'consommable')},
        ),
    ]
