# Generated by Django 5.0.1 on 2024-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0013_leasingclient_leasingconsommable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingclient',
            name='duree_contrat',
            field=models.CharField(max_length=10, verbose_name='Durée Contrat '),
        ),
    ]
