# Generated by Django 5.0.6 on 2024-06-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0018_livraisonclient_bordereau_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devea',
            name='autre_piece',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='facture_transitaire',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='fichier_dossier_dhl',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='fichier_facture_fornisseur',
        ),
        migrations.RemoveField(
            model_name='devea',
            name='numero_dhl',
        ),
        migrations.AddField(
            model_name='sav_request',
            name='recouvrement_hp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devea',
            name='livraisonclient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraisonclients_hp', to='serviceapresvente.livraisonclient'),
        ),
        migrations.AlterField(
            model_name='devea',
            name='status',
            field=models.CharField(choices=[('facturation HP, a completer', 'facturation HP, a completer'), ('Dossier HP  complet', 'Dossier HP  complet'), ('payé', 'payé'), ('non payé', 'non payé')], default='facturation HP, a completer', max_length=40, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='RecouvrementDevea',
            fields=[
                ('iddevearecouvrement', models.BigAutoField(primary_key=True, serialize=False)),
                ('deveaOrder', models.CharField(max_length=30, verbose_name='Order')),
                ('numero_dhl', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero DHL')),
                ('montant_facture_transitaire', models.FloatField(blank=True, null=True, verbose_name='Montant transitaire')),
                ('statut', models.CharField(choices=[('facturation HP, a completer', 'facturation HP, a completer'), ('Dossier HP  complet', 'Dossier HP  complet'), ('payé', 'payé'), ('non payé', 'non payé')], default='facturation HP, a completer', max_length=40, verbose_name='Statut')),
                ('facture_transitaire', models.ImageField(blank=True, null=True, upload_to='sav/facture_transitaire/%Y/%m/%d/')),
                ('fichier_dossier_dhl', models.ImageField(blank=True, null=True, upload_to='sav/dhl/%Y/%m/%d/')),
                ('autre_piece', models.ImageField(blank=True, null=True, upload_to='sav/autres_pieces/%Y/%m/%d/')),
                ('flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                #('deveas', models.ManyToManyField(blank=True, related_name='recouvrements', to='serviceapresvente.devea')),
            ],
        ),
    ]
