# Generated by Django 5.0.6 on 2024-06-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapresvente', '0020_remove_cloturedossier_recouvrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrementdevea',
            name='livraisonclient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livraisonclients_hp', to='serviceapresvente.livraisonclient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Devea',
        ),
    ]
