# Generated by Django 5.0.6 on 2024-05-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='aggree_terms',
            new_name='agree_terms',
        ),
    ]
