# Generated by Django 5.0.6 on 2024-10-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_lacation_profile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='oraganisation',
            new_name='organisation',
        ),
    ]
