# Generated by Django 5.0.6 on 2024-10-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_is_instance_customer_is_leasing_and_more'),
        ('accounts', '0005_rename_oraganisation_profile_organisation'),
    ]

    operations = [
    ]
