# Generated by Django 3.2.16 on 2023-05-29 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientleasing',
            fields=[
                ('idclientleasing', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('localite', models.CharField(max_length=100, verbose_name='Région')),
                ('refcontrat', models.CharField(max_length=45, unique=True, verbose_name='N° Contrat ')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date Contrat')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clientleasing',
                'verbose_name_plural': 'Clientleasings',
                'db_table': 'leasing_clientleasing',
                'ordering': ['nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('idconsommable', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('bordereausortie', models.CharField(max_length=30, verbose_name='Bordéreau de Sortie')),
                ('type', models.CharField(choices=[('Cartouche', 'Cartouche'), ('Photoconducteur', 'Photoconducteur'), ('Kits', 'Kits LexMark'), ('fuser', 'Fuser LexMark'), ('Papier', 'Papier RAM')], default='Papier', max_length=20, verbose_name='Catégorie')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Désignation')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('typeproduit', models.CharField(choices=[('HP', 'Produit HP'), ('LexMask', 'Produit LexMask'), ('Canon', 'Produit Canon')], default='LexMask', max_length=30, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'db_table': 'leasing_consommable',
                'ordering': ['-date', 'type', 'reference'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deploiement',
            fields=[
                ('iddeploiement', models.BigAutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(db_index=True, max_length=50, verbose_name='Site')),
                ('adresseip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse IP')),
                ('date_deploiement', models.DateField(blank=True, null=True, verbose_name='Date Deploiement')),
                ('clientleasing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.clientleasing')),
            ],
            options={
                'verbose_name': 'deploiement',
                'verbose_name_plural': 'deploiements',
                'db_table': 'leasing_deploiement',
                'ordering': ['iddeploiement'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistioriqueConsommable',
            fields=[
                ('idhistconsommable', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('bordereausortie', models.CharField(max_length=30, verbose_name='Bordéreau de Sortie')),
                ('reference', models.CharField(db_index=True, max_length=30, verbose_name='Référence')),
                ('designation', models.CharField(max_length=50, verbose_name='Désignation')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('typeproduit', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('action', models.CharField(max_length=100, verbose_name='Add_or_dell')),
                ('userLog', models.CharField(max_length=100, verbose_name='User_Id')),
            ],
            options={
                'verbose_name': 'Exploitation',
                'verbose_name_plural': 'Exploitations',
                'db_table': 'leasing_histioriqueconsommable',
                'ordering': ['date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listeimprimante',
            fields=[
                ('idlisteimprimante', models.BigAutoField(primary_key=True, serialize=False)),
                ('SN', models.CharField(max_length=50, verbose_name='Numeoro Série')),
                ('reference', models.CharField(db_index=True, max_length=50, verbose_name='Référence')),
                ('designation', models.CharField(db_index=True, max_length=50, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name='Date Acquisition')),
                ('garantie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Garantie')),
                ('endoflife', models.DateField(blank=True, null=True, verbose_name='End of Life')),
                ('userLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'listeimprimante',
                'verbose_name_plural': 'listeimprimantes',
                'db_table': 'leasing_listeimprimante',
                'ordering': ['reference'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('idexploitation', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('intervention', models.CharField(choices=[('Remplacement consommable', 'Remplacement consommable'), ('Releve fin du mois', 'Releve fin du mois'), ('Fourniture Carton Papier', 'Fourniture Carton Papier')], default='Fourniture Carton Papier', max_length=50, verbose_name='Intervention')),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('pourcentage_toner', models.CharField(blank=True, max_length=5, null=True, verbose_name='Toner (%) ')),
                ('ancien_index', models.IntegerField(blank=True, null=True)),
                ('nouvel_index', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('consommable', models.ManyToManyField(to='leasing.Consommable')),
                ('deploiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.deploiement')),
                ('userLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exploitation',
                'verbose_name_plural': 'Exploitations',
                'db_table': 'leasing_exploitation',
                'ordering': ['date'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='deploiement',
            name='listeimprimante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.listeimprimante'),
        ),
        migrations.AddField(
            model_name='deploiement',
            name='userLog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
