# Generated by Django 5.0.1 on 2024-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='consommable',
        #    name='marque',
        #    field=models.CharField(choices=[('HP', 'HP'), ('LEXMARK', 'LEXMARK'), ('Canon', 'Canon'), ('AUTRE', 'AUTRE')], default='LEXMARK', max_length=10, verbose_name='Marque'),
        #),
        migrations.AddField(
            model_name='consommable',
            name='modeleimprimante',
            field=models.CharField(default='', max_length=15, verbose_name='Modele Imprimante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consommable',
            name='produit',
            field=models.CharField(choices=[('Toner', 'Toner'), ('Tambour', 'Tambour'), ('Kit de Maintenance', 'Kit de Maintenance'), ('Papier RAM', 'Papier RAM'), ('Fuser', 'Fuser'), ('Flim Four', 'Flim Four')], default='Toner', max_length=20, verbose_name='Produit'),
        ),
    ]
