# Generated by Django 5.0.1 on 2024-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeimprimante',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listeimprimante',
            name='SN',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numeoro Série'),
        ),
    ]
