# Generated by Django 5.0.1 on 2024-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_remove_consommable_modele_consommable_marque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='modeleimprimante',
            field=models.CharField(default='', max_length=15, verbose_name='Modele Imprimante'),
        ),
    ]
