# Generated by Django 5.0.1 on 2024-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_listeimprimante_flag_alter_listeimprimante_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommable',
            name='model',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='Modele'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consommable',
            name='seuilLimite',
            field=models.IntegerField(default=5, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='designation',
            field=models.CharField(max_length=50, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='type',
            field=models.CharField(choices=[('Cartouche', 'Cartouche'), ('Photoconducteur', 'Photoconducteur'), ('Kits', 'Kits '), ('fuser LexMark', 'Fuser LexMark'), ('Papier RAM', 'Papier RAM')], default='Papier RAM', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='typeproduit',
            field=models.CharField(choices=[('HP', 'Produit HP'), ('Produit LexMask', 'Produit LexMask'), ('Produit Canon', 'Produit Canon')], default='Produit LexMask', max_length=30, verbose_name='Catégorie'),
        ),
    ]
