# Generated by Django 5.0.1 on 2024-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_consommable_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommable',
            name='modele',
        ),
        migrations.AddField(
            model_name='consommable',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('LEXMARK', 'LEXMARK'), ('Canon', 'Canon'), ('AUTRE', 'AUTRE')], default='LEXMARK', max_length=10, verbose_name='Marque'),
        ),
    ]
