# Generated by Django 5.0.1 on 2024-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_consommable_model_consommable_seuillimite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consommable',
            old_name='model',
            new_name='modele',
        ),
        migrations.AlterField(
            model_name='consommable',
            name='seuilLimite',
            field=models.IntegerField(default=5, verbose_name='Seuil'),
        ),
    ]
