# Generated by Django 5.0.6 on 2024-09-06 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_alter_exploitation_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionIncident',
            fields=[
                ('idhistconsommable', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('bordereausortie', models.CharField(max_length=30, verbose_name='Bordéreau de Sortie')),
                ('reference', models.CharField(db_index=True, max_length=30, verbose_name='Référence')),
                ('designation', models.CharField(max_length=50, verbose_name='Désignation')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('typeproduit', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('action', models.CharField(max_length=100, verbose_name='Add_or_dell')),
            ],
        ),
    ]
