# Generated by Django 5.0.6 on 2024-09-06 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_gestionincident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionincident',
            old_name='idhistconsommable',
            new_name='idincident',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='action',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='bordereausortie',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='gestionincident',
            name='typeproduit',
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='Statut',
            field=models.CharField(choices=[('Résolu', 'Résolu'), ('Non résolu', 'Non résolu')], default='Non résolu', max_length=15, verbose_name='Statut ticket'),
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='deploiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.deploiement'),
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='incident',
            field=models.CharField(choices=[('Défaut impression', 'Défaut impression'), ('Probleme Cartouche', 'Probleme Cartouche'), ('Défaut Alimentation', 'Défaut Alimentation')], default='Défaut impression', max_length=25, verbose_name='Statut ticket'),
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='userDSI',
            field=models.CharField(default='Leasing Team DSI', max_length=30, verbose_name='Leasing User'),
        ),
    ]
