# Generated by Django 5.0.6 on 2024-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_rename_idhistconsommable_gestionincident_idincident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeimprimante',
            name='numero_serie',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numero Série'),
        ),
    ]
