# Generated by Django 5.0.1 on 2024-03-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_exploitation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeCategorie',
            fields=[
                ('idcategorie', models.BigAutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=30, verbose_name='Catégorie')),
            ],
            options={
                'db_table': 'Leasing_typeCategorie',
                'ordering': ['categorie'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='consommable',
            name='typeproduit',
            field=models.CharField(max_length=30, verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='categorieproduit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='leasing.typecategorie', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='typeProduit',
            fields=[
                ('idperso', models.BigAutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Désignation')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.typecategorie')),
            ],
            options={
                'db_table': 'Leasing_typeProduit',
                'ordering': ['designation'],
                'managed': True,
            },
        ),
    ]
