# Generated by Django 5.0.6 on 2024-09-09 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_rename_pourcentage_toner_exploitation_niveau_hit_maintenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='id',
        ),
        migrations.AddField(
            model_name='gestionincident',
            name='teamsav',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='idmaintenance',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[(' OKAY ', 'OKAY'), ('NON OK', 'NON OK')], default=' OKAY ', max_length=15, verbose_name='Statut'),
        ),
    ]
