# Generated by Django 5.0.1 on 2024-03-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_typecategorie_alter_consommable_typeproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommable',
            name='categorieproduit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='leasing.typecategorie', verbose_name='Catégorie'),
        ),
    ]
