# Generated by Django 5.0.1 on 2024-03-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_alter_consommable_categorieproduit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeproduit',
            old_name='idperso',
            new_name='idtypeproduit',
        ),
        migrations.AlterField(
            model_name='consommable',
            name='bordereausortie',
            field=models.CharField(max_length=30, verbose_name='Bordéreau SOP'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
