# Generated by Django 5.0.6 on 2024-09-09 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_rename_statut_gestionincident_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionincident',
            name='observation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=200)], verbose_name='Observation'),
        ),
    ]
