# Generated by Django 5.0.6 on 2024-09-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_gestionincident_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionincident',
            old_name='userDSI',
            new_name='client_leasing',
        ),
    ]
