# Generated by Django 5.0.6 on 2024-09-09 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_rename_userdsi_gestionincident_client_leasing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionincident',
            old_name='teamsav',
            new_name='resp_dossier',
        ),
        migrations.AlterField(
            model_name='gestionincident',
            name='incident',
            field=models.CharField(choices=[('Défaut impression', 'Défaut impression'), ('Probleme Cartouche', 'Probleme Cartouche'), ('Défaut Alimentation', 'Défaut Alimentation')], default='Défaut impression', max_length=25, verbose_name='Type incident'),
        ),
        migrations.AlterField(
            model_name='gestionincident',
            name='observation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100)], verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='gestionincident',
            name='statut',
            field=models.CharField(choices=[('Résolu', 'Résolu'), ('Non résolu', 'Non résolu')], default='Non résolu', max_length=15, verbose_name='Statut incident'),
        ),
    ]
