# Generated by Django 5.0.6 on 2024-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_rename_teamsav_gestionincident_resp_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommable',
            name='designation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Désignation'),
        ),
    ]
