# Generated by Django 5.0.1 on 2024-09-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_remove_consommable_categorieproduit_and_more'),
        ('leasing', '0003_merge_20240905_1508'),
    ]

    operations = [
    ]
