# Generated by Django 5.0.1 on 2024-09-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeasingClient',
            new_name='Client',
        ),
    ]
