# Generated by Django 5.0.1 on 2024-09-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typecategorie',
            table='leasing_typeCategorie',
        ),
        migrations.AlterModelTable(
            name='typeproduit',
            table='leasing_typeProduit',
        ),
    ]
