# Generated by Django 5.0.1 on 2024-09-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_alter_typecategorie_table_alter_typeproduit_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeimprimante',
            name='userLog',
        ),
    ]
