# Generated by Django 4.2 on 2023-04-24 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_alter_exploitation_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommable',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Désignation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientleasing',
            name='nom',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='clientleasing',
            name='refcontrat',
            field=models.CharField(max_length=45, unique=True, verbose_name='N° Contrat '),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='reference',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='typeproduit',
            field=models.CharField(choices=[('HP', 'Produit HP'), ('LexMask', 'Produit LexMask'), ('Canon', 'Produit Canon')], default='LexMask', max_length=30, verbose_name='Catégirie'),
        ),
    ]
