# Generated by Django 4.2 on 2023-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_consommable_designation_alter_clientleasing_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommable',
            name='reference',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='type',
            field=models.CharField(choices=[('Cartouche', 'Cartouche'), ('Photoconducteur', 'Photoconducteur'), ('Kits', 'Kits LexMark'), ('fuser', 'Fuser LexMark'), ('Papier', 'Papier RAM')], default='Papier', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='typeproduit',
            field=models.CharField(choices=[('HP', 'Produit HP'), ('LexMask', 'Produit LexMask'), ('Canon', 'Produit Canon')], default='LexMask', max_length=30, verbose_name='Catégorie'),
        ),
    ]
