# Generated by Django 5.0.1 on 2024-09-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_categorie_remove_consommable_categorieproduit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='descriptif',
            new_name='description',
        ),
    ]
