# Generated by Django 5.0.1 on 2024-09-04 18:08

import apps.leasing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_rename_descriptif_categorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(choices=[('HP', 'Hp'), ('LEXMARK', 'LexMark'), ('CANON', 'CANON'), ('PAPIER', 'PAPIER')], max_length=10, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Descriptif'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='designation',
            field=models.CharField(max_length=25, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='reference',
            field=models.CharField(max_length=25, verbose_name='Référence'),
        ),
        migrations.RemoveField(
            model_name='consommable',
            name='categorieproduit',
        ),
        migrations.RemoveField(
            model_name='listeimprimante',
            name='categorieproduit',
        ),
        migrations.AddField(
            model_name='consommable',
            name='categorieproduit',
            field=models.ForeignKey(default=apps.leasing.models.Categorie.get_lexmark_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='leasing.categorie', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='listeimprimante',
            name='categorieproduit',
            field=models.ForeignKey(default=apps.leasing.models.Categorie.get_lexmark_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='leasing.categorie', verbose_name='Produit'),
        ),
    ]
