# Generated by Django 4.2 on 2023-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_alter_consommable_reference_alter_consommable_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommable',
            name='designation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='reference',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence'),
        ),
    ]
