# Generated by Django 4.2 on 2023-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_alter_consommable_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommable',
            options={'managed': True, 'ordering': ['-date', 'type', 'reference'], 'verbose_name': 'Consommable', 'verbose_name_plural': 'Consommables'},
        ),
        migrations.AddField(
            model_name='consommable',
            name='bordeausortie',
            field=models.CharField(default='BL001', max_length=30, verbose_name='Bordéreau de Sortie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consommable',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
