# Generated by Django 4.2 on 2023-04-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_consommable_options_consommable_bordeausortie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistioriqueConsommable',
            fields=[
                ('idistioriqueConsommable', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('bordeausortie', models.CharField(max_length=30, verbose_name='Bordéreau de Sortie')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Désignation')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('typeproduit', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
            ],
        ),
    ]
