# Generated by Django 4.2 on 2023-04-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_histioriqueconsommable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histioriqueconsommable',
            old_name='idistioriqueConsommable',
            new_name='idhistconsommable',
        ),
    ]
