# Generated by Django 4.2 on 2023-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_rename_idistioriqueconsommable_histioriqueconsommable_idhistconsommable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histioriqueconsommable',
            old_name='bordeausortie',
            new_name='bordereausortie',
        ),
        migrations.AddField(
            model_name='histioriqueconsommable',
            name='action',
            field=models.CharField(default='add', max_length=100, verbose_name='Add_or_dell'),
            preserve_default=False,
        ),
    ]
