# Generated by Django 4.2 on 2023-04-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_rename_bordeausortie_histioriqueconsommable_bordereausortie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consommable',
            old_name='bordeausortie',
            new_name='bordereausortie',
        ),
    ]
