# Generated by Django 4.2 on 2023-04-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_rename_bordeausortie_consommable_bordereausortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='histioriqueconsommable',
            name='userLog',
            field=models.CharField(default='0', max_length=100, verbose_name='User_Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='histioriqueconsommable',
            name='designation',
            field=models.CharField(max_length=50, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='histioriqueconsommable',
            name='reference',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Référence'),
        ),
    ]
