# Generated by Django 3.2.16 on 2023-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_histioriqueconsommable_userlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleasing',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='exploitation',
            name='intervention',
            field=models.CharField(choices=[('Remplacement consommable', 'Remplacement consommable'), ('Releve fin du mois', 'Releve fin du mois'), ('Fourniture Carton Papier', 'Fourniture Carton Papier')], default='Fourniture Carton Papier', max_length=50, verbose_name='Intervention'),
        ),
    ]
